// <auto-generated />
using System;
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260508101919_TestDirectionAdded")]
    partial class TestDirectionAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Data.Entities.TblDictionaryKeys", b =>
                {
                    b.Property<int>("IdDictionaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DictionaryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IsEditable")
                        .HasColumnType("int");

                    b.Property<string>("KeyDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("IdDictionaryKey");

                    b.ToTable("TblDictionaryKeys", (string)null);
                });

            modelBuilder.Entity("Data.Entities.TblDictionaryValues", b =>
                {
                    b.Property<int>("IdDictionaryValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DictionaryValue")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("IdDictionaryKey")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ValueDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.HasKey("IdDictionaryValue");

                    b.ToTable("TblDictionaryValues", (string)null);
                });

            modelBuilder.Entity("Data.Entities.TblTest", b =>
                {
                    b.Property<int>("IdTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BlankType")
                        .HasColumnType("int");

                    b.Property<int>("ConventionalUnitID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CurveTypeID")
                        .HasColumnType("int");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<int>("DirectionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSpecialSolution")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MethodID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("NoOfReagents")
                        .HasColumnType("int");

                    b.Property<int>("SIUnitID")
                        .HasColumnType("int");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("TestSequence")
                        .HasColumnType("int");

                    b.Property<int>("UniqueIDTest")
                        .HasColumnType("int");

                    b.HasKey("IdTest");

                    b.ToTable("TblTest", (string)null);
                });

            modelBuilder.Entity("Data.Entities.TblTestDetails", b =>
                {
                    b.Property<int>("IdTestDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutoDilutionRatio")
                        .HasColumnType("int");

                    b.Property<int>("CorelationA")
                        .HasColumnType("int");

                    b.Property<int>("CorelationB")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdTest")
                        .HasColumnType("int");

                    b.Property<int>("IncubationTime")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelayedR2")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("LastReagentBlank")
                        .HasColumnType("double");

                    b.Property<double>("Linearity")
                        .HasColumnType("double");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryFilterID")
                        .HasColumnType("int");

                    b.Property<int>("R1Volume")
                        .HasColumnType("int");

                    b.Property<int>("R2Volume")
                        .HasColumnType("int");

                    b.Property<int>("ReadEndCycle")
                        .HasColumnType("int");

                    b.Property<int>("ReadStartCycle")
                        .HasColumnType("int");

                    b.Property<int>("ReadingTime")
                        .HasColumnType("int");

                    b.Property<double>("ReagentBlankHigh")
                        .HasColumnType("double");

                    b.Property<double>("ReagentBlankLow")
                        .HasColumnType("double");

                    b.Property<double>("SampleVolume")
                        .HasColumnType("double");

                    b.Property<int>("SecondaryFilterID")
                        .HasColumnType("int");

                    b.Property<int>("StirrerSpeedR2")
                        .HasColumnType("int");

                    b.Property<int>("StirrerSpeedSample")
                        .HasColumnType("int");

                    b.Property<double>("SubstrateDepletion")
                        .HasColumnType("double");

                    b.HasKey("IdTestDetails");

                    b.ToTable("TblTestDetails", (string)null);
                });

            modelBuilder.Entity("Data.Entities.TblUser", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUser");

                    b.ToTable("TblUser", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
