// <auto-generated />
using System;
using GrpcGreeter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrpcGreeter.Migrations
{
    [DbContext(typeof(FAA_DbContext))]
    [Migration("20260305060222_GRPCEfmigrationsS1")]
    partial class GRPCEfmigrationsS1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GrpcGreeter.Models.TblResults", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("ResultTime")
                        .HasColumnType("time(6)");

                    b.Property<long>("SampleId")
                        .HasColumnType("bigint");

                    b.Property<short>("TestId")
                        .HasColumnType("smallint");

                    b.HasKey("ResultId");

                    b.ToTable("TblResults");
                });
#pragma warning restore 612, 618
        }
    }
}
